name: OverseerAdmin
author: AndyAndreiH
authors: [Migs84]
website: http://katgamestudios.com/
main: com.katgamestudios.andyandreih.overseer.admin.OverseerAdmin
version: 0.1
depend: [OverseerMain]
database: false
commands:
   tp:
      description: Teleports the player
      usage: /tp <srcPlayer> <dstPlayer/dstLocation>
   freeze:
      description: Freezes the player
      usage: /freeze <player>
   unfreeze:
      description: Unfreezes the player
      usage: /unfreeze <player>
permissions:
   overseer.admin.*:
      description: Master permission node
      default: false
      children:
         overseer.admin.adminchannel: true
         overseer.admin.tp: true
         overseer.admin.freeze: true
         overseer.admin.unfreeze: true
         overseer.admin.unfreeze.self: true
   overseer.admin.adminchannel:
      description: Gives access to the admin message channel
      default: false
   overseer.admin.tp:
      description: Gives access to the teleportation command
      default: false
   overseer.admin.freeze:
      description: Gives access to the freezing command
      default: false
   overseer.admin.unfreeze:
      description: Gives access to the unfreezing command
      default: false
   overseer.admin.unfreeze.self:
      description: Allows the player to unfreeze self
      default: false